"""
Centralised UI label translations for BG (Bulgarian) and EN (English).
Usage in any module:
    from labels import L
    # L is a function: L(lang, 'key')
    # or just do: labels = get_labels(lang) then labels['key']
"""

LABELS = {
    'bg': {
        # ── App-level ─────────────────────────────────────────────────────────────
        'page_title': 'Визуализация на исторически писма',
        'app_title': 'Визуализация на исторически писма (TEI XML)',
        'language_label': '🌐 Език / Language',
        # tabs
        'tab_docs': 'Документи',
        'tab_map': 'Карта',
        'tab_stats': 'Статистика',
        'tab_search': 'Търсене по Shelfmark',
        'tab_network': 'Мрежов анализ',
        'tab_geo_network': 'Географска мрежа',
        'tab_topics': 'Теми и думи',
        'tab_commodity': 'Стокови потоци',
        'tab_temporal': 'Темпорален анализ',
        # docs tab
        'sidebar_correspondence': 'Избор на кореспонденция',
        'select_sender': 'Изберете изпращач:',
        'select_addressee': 'Изберете получател:',
        'none_option': '(Няма)',
        'select_doc': 'Изберете документ:',
        'doc_label': 'Документ:',
        'sender_info': 'Информация за изпращача',
        'addressee_info': 'Информация за получателя',
        'name': 'Име',
        'location': 'Местоположение',
        'date': 'Дата',
        'main_topics': 'Основни теми',
        'keywords': 'Ключови думи',
        'other_info': 'Друга информация',
        'no_data': 'Няма данни',
        'mentioned_places': 'Споменати места',
        'mentioned_persons': 'Споменати личности',
        'place_details': 'Подробности за споменатите места:',
        'no_coords': 'Няма координатни данни за споменатите места',
        'no_places': 'Няма споменати места',
        'more_info': 'Повече информация',
        'no_docs_found': 'Няма намерени документи за кореспонденция между {s} и {a}.',
        'select_addressee_prompt': 'Моля, изберете получател.',
        'select_sender_prompt': 'Моля, изберете изпращач.',
        'found_docs': 'Намерени {n} документа между {s} и {a}:',
        # map tab
        'map_header': 'Карта на всички споменати места',
        'map_settings': 'Настройки на картата',
        'map_height_label': 'Височина на картата',
        'fullscreen_cb': 'Покажи в пълен екран',
        'fullscreen_title': 'Покажи в пълен екран',
        'fullscreen_cancel': 'Излез от пълен екран',
        'mention_count_label': 'Брой споменавания:',
        'mentions': 'споменавания',
        'add_info': 'Допълнителна информация',
        'no_coord_places': 'Няма споменати места с координати.',
        'clusters_label': 'Споменати места',
        'map_legend': (
            "**Легенда на картата:**\n"
            "- 🔴 Червени маркери: 5+ споменавания\n"
            "- 🟠 Оранжеви маркери: 3-4 споменавания\n"
            "- 🟢 Зелени маркери: 2 споменавания\n"
            "- 🔵 Сини маркери: 1 споменаване\n\n"
            "**Слоеве на картата:**\n"
            "- **OpenStreetMap**: Стандартна карта\n"
            "- **Topographic**: Топографска карта с релеф\n"
            "- **Terrain**: Терен с релефни данни\n"
            "- **Satellite**: Сателитни изображения"
        ),
        # stats tab
        'stats_header': 'Статистика',
        'sender_dist': 'Разпределение на документите по изпращач',
        'docs_by_sender_title': 'Брой документи по изпращач',
        'docs_by_addressee': 'Брой документи по получател',
        'addressee_col': 'Получател',
        'doc_count_col': 'Брой документи',
        'no_addressee_data': 'Няма данни за получатели.',
        'top_keywords': 'Най-често споменавани ключови думи',
        'keyword_col': 'Ключова дума',
        'mention_col': 'Брой споменавания',
        'related_docs_hdr': 'Документи свързани с ключовата дума: **{kw}**',
        'found_shelfmarks': 'Намерените shelfmarks ({n}):',
        'no_docs_keyword': 'Няма намерени документи за тази ключова дума.',
        'select_keyword': 'Моля, изберете ключова дума от таблицата.',
        'no_keywords_filter': 'Няма ключови думи след филтрация.',
        'no_keywords': 'Няма ключови думи.',
        'no_stats': 'Няма данни за статистика.',
        # search tab
        'search_header': 'Търсене по Shelfmark',
        'search_input': 'Въведете Shelfmark или част от него:',
        'select_shelfmark': 'Изберете Shelfmark:',
        'shelfmark_not_found': 'Документът с този Shelfmark не беше намерен.',
        'select_shelfmark_prompt': 'Моля, изберете Shelfmark от списъка.',
        # module tab headers (used in app.py)
        'network_header': 'Мрежов анализ на кореспонденциите',
        'geo_header': 'Географска мрежа на места',
        'topics_header': 'Анализ на теми и ключови думи',
        'commodity_header': 'Анализ на стоковите потоци',
        'temporal_header': 'Темпорален анализ на комуникациите',

        # ── network_analysis.py ───────────────────────────────────────────────────
        'na_func_header': '📬 Мрежов анализ на кореспонденциите',
        'na_interactive_net': '🔗 Интерактивна мрежа',
        'na_top_corr': '📊 Топ кореспонденти',
        'na_top10_label': 'Топ 10 по общо връзки:',
        'na_centrality_label': 'Мерки за централност:',
        'na_dist_analysis': '📈 Анализ на разпределението',
        'na_letters_label': 'Писма',
        'na_received_tooltip': 'Получени',
        'na_sent_tooltip': 'Изпратени',
        'na_total_tooltip': 'Общо връзки',
        'na_error': '⚠️ Грешка при генериране на мрежовия анализ',
        'na_subtitle': 'Анализ на мрежата от кореспонденции между различни лица',
        'na_settings': '🎛️ Настройки на мрежата',
        'na_min_conn': 'Минимален брой връзки:',
        'na_min_conn_help': 'Показвай само лица с поне толкова връзки',
        'na_layout': 'Алгоритъм за подредба:',
        'na_layout_help': 'Различни алгоритми за подредба на мрежата',
        'na_node_size': 'Размер на възлите:',
        'na_node_size_help': 'Скалиране на размера на възлите',
        'na_show_weights': 'Показвай тегла на връзките',
        'na_show_weights_help': 'Показвай броя писма между лицата',
        'na_total_persons': '👥 Общо лица',
        'na_total_persons_help': 'Брой уникални лица в мрежата',
        'na_total_edges': '🔗 Общо връзки',
        'na_total_edges_help': 'Брой връзки между лицата',
        'na_total_letters': '📬 Общо писма',
        'na_total_letters_help': 'Общ брой разменени писма',
        'na_density': '📊 Плътност',
        'na_density_help': 'Плътност на мрежата (0-1)',
        'na_no_data': '🚫 Няма данни за показване с текущите настройки. Намалете минималния брой връзки.',
        'na_person_col': 'Лице',
        'na_total_conn_col': 'Общо връзки',
        'na_received_col': 'Получени писма',
        'na_sent_col': 'Изпратени писма',
        'na_conn_dist_title': 'Разпределение на връзките',
        'na_conn_dist_x': 'Брой връзки',
        'na_conn_dist_y': 'Честота',
        'na_top10_title': 'Топ 10 лица по връзки',
        'na_advanced': 'Усъвършенстван анализ на мрежата от кореспонденции',

        # ── geographical_network.py ───────────────────────────────────────────────
        'geo_desc': (
            "**Възли (Nodes):** Места споменати в писмата или произход/дестинация на писма  \n"
            "**Връзки (Edges):** Писма или търговски маршрути, свързващи местата  \n"
            "**Визуализация:** Карта с дъги, показващи комуникационни или търговски потоци"
        ),
        'geo_inner_map': '🗺️ Карта с дъги',
        'geo_inner_network': '🕸️ Мрежова диаграма',
        'geo_inner_stats': '📊 Статистика',
        'geo_sidebar_settings': '🗺️ Настройки на картата',
        'geo_fullscreen_info': '🖥️ Картата винаги се показва в пълноекранен режим',
        'geo_fullscreen_map_hdr': '### 🗺️ Пълноекранна карта на всички споменати места',
        'geo_total_mentions': 'Общо споменавания',
        'geo_as_sender': 'Като изпращач',
        'geo_as_addressee': 'Като получател',
        'geo_mentioned_in': 'Споменато в писма',
        'geo_neighbors': 'Съседи',
        'geo_mentions_count': 'Споменавания',
        'geo_connections': 'Връзки',
        'geo_legend_blue': '**🔵 Сини маркери:** Всички места',
        'geo_legend_red': '**🔴 Червени линии:** Връзки между места (дебелина = брой връзки)',
        'geo_subheader': 'Географска мрежа (Мрежа на места)',
        'geo_no_data': 'Няма достатъчно данни за създаване на географска мрежа.',
        'geo_map_header': 'Интерактивна карта с географски връзки',
        'geo_no_coords': 'Няма места с координати за показване на картата.',
        'geo_map_height': 'Височина на картата',
        'geo_min_conn': 'Минимален брой връзки:',
        'geo_fullscreen': 'Пълен екран',
        'geo_fullscreen_cancel': 'Изход от пълен екран',
        'geo_mentions': 'Споменавания: {n}',
        'geo_network_diag': 'Мрежова диаграма на места',
        'geo_no_diag': 'Няма данни за създаване на мрежова диаграма.',
        'geo_net_title': 'Географска мрежа на места',
        'geo_node_note': 'Размерът на възлите е пропорционален на броя споменавания',
        'geo_stats_header': 'Статистика за географската мрежа',
        'geo_total_places': 'Общо места',
        'geo_places_coords': 'Места с координати',
        'geo_total_conn': 'Общо връзки',
        'geo_total_comm': 'Общо комуникации',
        'geo_top_places': 'Най-свързани места',
        'geo_place_col': 'Място',
        'geo_conn_col': 'Брой връзки',
        'geo_top_connected': 'Най-свързани места',
        'geo_conn_analysis': 'Анализ на връзките',
        'geo_place1_col': 'Място 1',
        'geo_place2_col': 'Място 2',
        'geo_top_links': 'Най-силни връзки между места',

        # ── topics_keywords_analysis.py ───────────────────────────────────────────
        'tk_desc': (
            "**Анализ:** Мрежа на съвместно срещане на теми и ключови думи в писмата  \n"
            "**Възли:** Основни теми и ключови думи  \n"
            "**Връзки:** Съвместно споменаване в едно и също писмо  \n"
            "**Размер на възела:** Честота на споменаване"
        ),
        'tk_inner_network': '🕸️ Мрежа',
        'tk_inner_freq': '📊 Честота',
        'tk_inner_analysis': '🔍 Анализ',
        'tk_subheader': 'Анализ на теми и ключови думи',
        'tk_no_data': 'Няма достатъчно данни за анализ на теми и ключови думи.',
        'tk_network_header': 'Мрежа на теми и ключови думи',
        'tk_no_links': 'Няма връзки между темите за визуализация.',
        'tk_settings': 'Настройки',
        'tk_min_cooc': 'Минимално съвместно срещане:',
        'tk_layout': 'Алгоритъм за подредба:',
        'tk_no_match': 'Няма връзки, които отговарят на критерия.',
        'tk_freq_label': 'Честота: {n}',
        'tk_conn_label': 'Връзки: {n}',
        'tk_colorbar_title': 'Честота',
        'tk_net_title': 'Мрежа на теми и ключови думи',
        'tk_shown': 'Показани {n} теми с минимум {m} съвместни споменавания',
        'tk_freq_header': 'Честота на теми и ключови думи',
        'tk_no_freq': 'Няма данни за честота на темите.',
        'tk_topic_col': 'Тема/Ключова дума',
        'tk_freq_col': 'Честота',
        'tk_top20': 'Топ 20 най-чести теми',
        'tk_freq_dist': 'Разпределение на честотата',
        'tk_freq_dist_title': 'Най-чести теми и ключови думи',
        'tk_stats': 'Статистики',
        'tk_total': 'Общо теми/думи',
        'tk_avg_freq': 'Средна честота',
        'tk_max_freq': 'Най-честа',
        'tk_unique': 'Уникални (1x)',
        'tk_conn_analysis': 'Детайлен анализ на връзките',
        'tk_no_conn': 'Няма данни за анализ на връзките.',
        'tk_topic1_col': 'Тема 1',
        'tk_topic2_col': 'Тема 2',
        'tk_cooc_col': 'Съвместни споменавания',
        'tk_strong_links': 'Най-силни връзки',
        'tk_conn_dist': 'Разпределение на силата на връзките',
        'tk_conn_dist_title': 'Разпределение на съвместните споменавания',
        'tk_metrics': 'Мрежови метрики',
        'tk_degree_centrality': 'Степенна централност',
        'tk_betweenness': 'Посредническа централност',
        'tk_closeness': 'Близостна централност',
        'tk_topic_row': 'Тема',
        'tk_top15': 'Топ 15 теми по централност',
        'tk_nodes': 'Възли в мрежата',
        'tk_edges': 'Връзки в мрежата',
        'tk_density': 'Плътност',
        'tk_avg_path': 'Средна дистанция',
        'tk_components': 'Компоненти',

        # ── commodity_analysis.py ─────────────────────────────────────────────────
        'ca_desc': (
            "**Анализ:** Мрежа на стоковите потоци между места  \n"
            "**Възли:** Стоки (ключови думи) и места  \n"
            "**Връзки:** Споменаване на стока в контекста на място  \n"
            "**Цел:** Проследяване на търговските маршрути и стокообмена"
        ),
        'ca_inner_network': '🕸️ Двустранна мрежа',
        'ca_inner_flows': '📊 Потоци',
        'ca_inner_analysis': '🔍 Анализ',
        'ca_annotation': '🟡 Стоки | 🔵 Места',
        'ca_subheader': 'Анализ на стоковите потоци',
        'ca_no_data': 'Няма достатъчно данни за анализ на стоковите потоци.',
        'ca_net_header': 'Двустранна мрежа: Стоки ↔ Места',
        'ca_no_net': 'Няма данни за създаване на мрежа.',
        'ca_settings': 'Настройки',
        'ca_min_mentions': 'Минимален брой споменавания:',
        'ca_show_labels': 'Покажи етикети',
        'ca_layout_type': 'Тип на подредбата:',
        'ca_no_match': 'Няма връзки, които отговарят на критерия.',
        'ca_type_commodity': 'Стока',
        'ca_type_place': 'Място',
        'ca_conn_label': 'Връзки: {n}',
        'ca_net_title': 'Двустранна мрежа: Стоки ↔ Места',
        'ca_flows_header': 'Анализ на стоковите потоци',
        'ca_top_commodities': 'Топ стоки по брой места',
        'ca_commodity_col': 'Стока',
        'ca_num_places_col': 'Брой места',
        'ca_total_mentions_col': 'Общо споменавания',
        'ca_top_comm_title': 'Топ 10 стоки по географско разпространение',
        'ca_top_places': 'Топ места по брой стоки',
        'ca_place_col': 'Място',
        'ca_num_commodities_col': 'Брой стоки',
        'ca_top_places_title': 'Топ 10 места по стоково разнообразие',
        'ca_network_analysis': 'Мрежов анализ на стоковите потоци',
        'ca_no_net_analysis': 'Няма данни за мрежов анализ.',
        'ca_node_col': 'Възел',
        'ca_degree_col': 'Степенна централност',
        'ca_betweenness_col': 'Посредническа централност',
        'ca_connections_col': 'Връзки',
        'ca_top_commodities_central': 'Топ стоки по централност',
        'ca_top_places_central': 'Топ места по централност',
        'ca_net_stats': 'Статистики на мрежата',
        'ca_commodities_metric': 'Стоки',
        'ca_places_metric': 'Места',
        'ca_edges_metric': 'Връзки',
        'ca_density_metric': 'Гъстота',
        'ca_weight_dist': 'Разпределение на силата на връзките',
        'ca_weight_dist_title': 'Разпределение на броя споменавания стока-място',
        'ca_weight_x': 'Брой споменавания',
        'ca_weight_y': 'Честота',

        # ── temporal_analysis.py ───────────────────────────────────────────────────
        'ta_desc': (
            "**Анализ:** Еволюция на комуникационните мрежи във времето  \n"
            "**Възли:** Изпращачи и получатели  \n"
            "**Връзки:** Писма с времеви марки  \n"
            "**Цел:** Проследяване на промените в комуникационните модели"
        ),
        'ta_inner_timeline': '📅 Времева линия',
        'ta_inner_network': '🕸️ Темпорална мрежа',
        'ta_inner_analysis': '🔍 Анализ',
        'ta_heatmap_header': 'Heatmap на комуникационна активност',
        'ta_month': 'Месец',
        'ta_year_str': 'Година',
        'ta_color': 'Брой писма',
        'ta_subheader': 'Темпорален анализ на комуникациите',
        'ta_no_data': 'Няма достатъчно данни с дати за темпорален анализ.',
        'ta_timeline_header': 'Времева линия на кореспонденцията',
        'ta_no_dates': 'Няма писма с валидни дати.',
        'ta_settings': 'Настройки',
        'ta_period': 'Период:',
        'ta_groupby': 'Групиране по:',
        'ta_senders': 'Изпращачи:',
        'ta_no_period': 'Няма данни за избрания период.',
        'ta_date_label': 'Дата',
        'ta_month_label': 'Месец',
        'ta_year_label': 'Година',
        'ta_letters_over_time': 'Брой писма във времето (групирано по {g})',
        'ta_letters_y': 'Брой писма',
        'ta_month_x': 'Месец',
        'ta_year_x': 'Година',
        'ta_color_label': 'Брой писма',
        'ta_net_header': 'Еволюция на комуникационната мрежа',
        'ta_no_net': 'Няма данни за темпорална мрежа.',
        'ta_window_size': 'Размер на времевия прозорец (дни):',
        'ta_animation': 'Анимация',
        'ta_layout': 'Алгоритъм за подредба:',
        'ta_select_date': 'Избери дата за централна точка:',
        'ta_no_window': 'Няма писма в периода {s} - {e}',
        'ta_sent_label': 'Изпратени: {n}',
        'ta_received_label': 'Получени: {n}',
        'ta_activity_label': 'Общо активност: {n}',
        'ta_net_title': 'Комуникационна мрежа: {s} - {e} ({n} писма)',
        'ta_period_stats': 'Статистики за периода',
        'ta_letters_metric': 'Писма',
        'ta_participants_metric': 'Участници',
        'ta_links_metric': 'Връзки',
        'ta_density_metric': 'Плътност',
        'ta_analysis_header': 'Темпорален анализ на комуникациите',
        'ta_no_analysis': 'Няма данни за темпорален анализ.',
        'ta_activity_header': 'Активност по участници',
        'ta_sender_y': 'Изпращач',
        'ta_activity_title': 'Активност на изпращачите във времето',
        'ta_patterns': 'Комуникационни модели',
        'ta_top_links': 'Топ комуникационни връзки',
        'ta_letters_dist': 'Разпределение на писмата във времето',
        'ta_evolution_header': 'Еволюция на мрежовите метрики',
        'ta_participants_trace': 'Брой участници',
        'ta_letters_trace': 'Брой писма',
        'ta_evolution_title': 'Еволюция на мрежата во времето',
        'ta_period_axis': 'Период',
        'ta_participants_axis': 'Брой участници',
        'ta_letters_axis': 'Брой писма',
        'ta_detail_periods': 'Детайлни метрики по периоди',
        'ta_anim_info': 'Анимацията на темпоралната мрежа ще бъде имплементирана в бъдеща версия. Моля, използвайте статичния режим за сега.',
    },

    'en': {
        # ── App-level ─────────────────────────────────────────────────────────────
        'page_title': 'Historical Letters Visualization',
        'app_title': 'Historical Letters Visualization (TEI XML)',
        'language_label': '🌐 Language / Език',
        # tabs
        'tab_docs': 'Documents',
        'tab_map': 'Map',
        'tab_stats': 'Statistics',
        'tab_search': 'Search by Shelfmark',
        'tab_network': 'Network Analysis',
        'tab_geo_network': 'Geographical Network',
        'tab_topics': 'Topics & Keywords',
        'tab_commodity': 'Commodity Flows',
        'tab_temporal': 'Temporal Analysis',
        # docs tab
        'sidebar_correspondence': 'Select Correspondence',
        'select_sender': 'Select sender:',
        'select_addressee': 'Select addressee:',
        'none_option': '(None)',
        'select_doc': 'Select document:',
        'doc_label': 'Document:',
        'sender_info': 'Sender Information',
        'addressee_info': 'Addressee Information',
        'name': 'Name',
        'location': 'Location',
        'date': 'Date',
        'main_topics': 'Main Topics',
        'keywords': 'Keywords',
        'other_info': 'Other Information',
        'no_data': 'No data',
        'mentioned_places': 'Mentioned Places',
        'mentioned_persons': 'Mentioned Persons',
        'place_details': 'Details of mentioned places:',
        'no_coords': 'No coordinate data for mentioned places',
        'no_places': 'No mentioned places',
        'more_info': 'More information',
        'no_docs_found': 'No documents found for correspondence between {s} and {a}.',
        'select_addressee_prompt': 'Please select an addressee.',
        'select_sender_prompt': 'Please select a sender.',
        'found_docs': 'Found {n} documents between {s} and {a}:',
        # map tab
        'map_header': 'Map of All Mentioned Places',
        'map_settings': 'Map Settings',
        'map_height_label': 'Map height',
        'fullscreen_cb': 'Show fullscreen',
        'fullscreen_title': 'Show fullscreen',
        'fullscreen_cancel': 'Exit fullscreen',
        'mention_count_label': 'Number of mentions:',
        'mentions': 'mentions',
        'add_info': 'Additional information',
        'no_coord_places': 'No mentioned places with coordinates.',
        'clusters_label': 'Mentioned places',
        'map_legend': (
            "**Map Legend:**\n"
            "- 🔴 Red markers: 5+ mentions\n"
            "- 🟠 Orange markers: 3-4 mentions\n"
            "- 🟢 Green markers: 2 mentions\n"
            "- 🔵 Blue markers: 1 mention\n\n"
            "**Map Layers:**\n"
            "- **OpenStreetMap**: Standard map\n"
            "- **Topographic**: Topographic map with relief\n"
            "- **Terrain**: Terrain with elevation data\n"
            "- **Satellite**: Satellite imagery"
        ),
        # stats tab
        'stats_header': 'Statistics',
        'sender_dist': 'Distribution of documents by sender',
        'docs_by_sender_title': 'Number of documents by sender',
        'docs_by_addressee': 'Number of documents by addressee',
        'addressee_col': 'Addressee',
        'doc_count_col': 'Number of Documents',
        'no_addressee_data': 'No addressee data.',
        'top_keywords': 'Most frequently mentioned keywords',
        'keyword_col': 'Keyword',
        'mention_col': 'Number of Mentions',
        'related_docs_hdr': 'Documents related to keyword: **{kw}**',
        'found_shelfmarks': 'Found shelfmarks ({n}):',
        'no_docs_keyword': 'No documents found for this keyword.',
        'select_keyword': 'Please select a keyword from the table.',
        'no_keywords_filter': 'No keywords after filtering.',
        'no_keywords': 'No keywords.',
        'no_stats': 'No statistics data.',
        # search tab
        'search_header': 'Search by Shelfmark',
        'search_input': 'Enter Shelfmark or part of it:',
        'select_shelfmark': 'Select Shelfmark:',
        'shelfmark_not_found': 'Document with this Shelfmark was not found.',
        'select_shelfmark_prompt': 'Please select a Shelfmark from the list.',
        # module tab headers
        'network_header': 'Correspondence Network Analysis',
        'geo_header': 'Geographical Network of Places',
        'topics_header': 'Topics and Keywords Analysis',
        'commodity_header': 'Commodity Flow Analysis',
        'temporal_header': 'Temporal Analysis of Communications',

        # ── network_analysis.py ───────────────────────────────────────────────────
        'na_func_header': '📬 Correspondence Network Analysis',
        'na_interactive_net': '🔗 Interactive Network',
        'na_top_corr': '📊 Top Correspondents',
        'na_top10_label': 'Top 10 by total connections:',
        'na_centrality_label': 'Centrality measures:',
        'na_dist_analysis': '📈 Distribution Analysis',
        'na_letters_label': 'Letters',
        'na_received_tooltip': 'Received',
        'na_sent_tooltip': 'Sent',
        'na_total_tooltip': 'Total connections',
        'na_error': '⚠️ Error generating network analysis',
        'na_subtitle': 'Analysis of the correspondence network between persons',
        'na_settings': '🎛️ Network Settings',
        'na_min_conn': 'Minimum number of connections:',
        'na_min_conn_help': 'Show only persons with at least this many connections',
        'na_layout': 'Layout algorithm:',
        'na_layout_help': 'Different algorithms for arranging the network',
        'na_node_size': 'Node size:',
        'na_node_size_help': 'Scale factor for node sizes',
        'na_show_weights': 'Show edge weights',
        'na_show_weights_help': 'Show the number of letters between persons',
        'na_total_persons': '👥 Total persons',
        'na_total_persons_help': 'Number of unique persons in the network',
        'na_total_edges': '🔗 Total connections',
        'na_total_edges_help': 'Number of connections between persons',
        'na_total_letters': '📬 Total letters',
        'na_total_letters_help': 'Total number of exchanged letters',
        'na_density': '📊 Density',
        'na_density_help': 'Network density (0-1)',
        'na_no_data': '🚫 No data to display with current settings. Reduce the minimum connections.',
        'na_person_col': 'Person',
        'na_total_conn_col': 'Total connections',
        'na_received_col': 'Received letters',
        'na_sent_col': 'Sent letters',
        'na_conn_dist_title': 'Connection distribution',
        'na_conn_dist_x': 'Number of connections',
        'na_conn_dist_y': 'Frequency',
        'na_top10_title': 'Top 10 persons by connections',
        'na_advanced': 'Advanced correspondence network analysis',

        # ── geographical_network.py ───────────────────────────────────────────────
        'geo_desc': (
            "**Nodes:** Places mentioned in letters or origin/destination of letters  \n"
            "**Edges:** Letters or trade routes connecting the places  \n"
            "**Visualization:** Map with arcs showing communication or trade flows"
        ),
        'geo_inner_map': '🗺️ Map with Arcs',
        'geo_inner_network': '🕸️ Network Diagram',
        'geo_inner_stats': '📊 Statistics',
        'geo_sidebar_settings': '🗺️ Map Settings',
        'geo_fullscreen_info': '🖥️ Map is always shown in full-screen mode',
        'geo_fullscreen_map_hdr': '### 🗺️ Full-screen map of all mentioned places',
        'geo_total_mentions': 'Total mentions',
        'geo_as_sender': 'As sender',
        'geo_as_addressee': 'As addressee',
        'geo_mentioned_in': 'Mentioned in letters',
        'geo_neighbors': 'Neighbors',
        'geo_mentions_count': 'Mentions',
        'geo_connections': 'Connections',
        'geo_legend_blue': '**🔵 Blue markers:** All places',
        'geo_legend_red': '**🔴 Red lines:** Connections between places (thickness = number of connections)',
        'geo_subheader': 'Geographical Network (Place Network)',
        'geo_no_data': 'Not enough data to create a geographical network.',
        'geo_map_header': 'Interactive map with geographical connections',
        'geo_no_coords': 'No places with coordinates to display on the map.',
        'geo_map_height': 'Map height',
        'geo_min_conn': 'Minimum number of connections:',
        'geo_fullscreen': 'Fullscreen',
        'geo_fullscreen_cancel': 'Exit fullscreen',
        'geo_mentions': 'Mentions: {n}',
        'geo_network_diag': 'Network diagram of places',
        'geo_no_diag': 'No data to create a network diagram.',
        'geo_net_title': 'Geographical network of places',
        'geo_node_note': 'Node size is proportional to the number of mentions',
        'geo_stats_header': 'Geographical network statistics',
        'geo_total_places': 'Total places',
        'geo_places_coords': 'Places with coordinates',
        'geo_total_conn': 'Total connections',
        'geo_total_comm': 'Total communications',
        'geo_top_places': 'Most connected places',
        'geo_place_col': 'Place',
        'geo_conn_col': 'Number of connections',
        'geo_top_connected': 'Most connected places',
        'geo_conn_analysis': 'Connection analysis',
        'geo_place1_col': 'Place 1',
        'geo_place2_col': 'Place 2',
        'geo_top_links': 'Strongest connections between places',

        # ── topics_keywords_analysis.py ───────────────────────────────────────────
        'tk_desc': (
            "**Analysis:** Co-occurrence network of topics and keywords in letters  \n"
            "**Nodes:** Main topics and keywords  \n"
            "**Edges:** Co-occurrence in the same letter  \n"
            "**Node size:** Frequency of occurrence"
        ),
        'tk_inner_network': '🕸️ Network',
        'tk_inner_freq': '📊 Frequency',
        'tk_inner_analysis': '🔍 Analysis',
        'tk_subheader': 'Topics and Keywords Analysis',
        'tk_no_data': 'Not enough data for topics and keywords analysis.',
        'tk_network_header': 'Topics and keywords network',
        'tk_no_links': 'No connections between topics for visualization.',
        'tk_settings': 'Settings',
        'tk_min_cooc': 'Minimum co-occurrence:',
        'tk_layout': 'Layout algorithm:',
        'tk_no_match': 'No connections match the criteria.',
        'tk_freq_label': 'Frequency: {n}',
        'tk_conn_label': 'Connections: {n}',
        'tk_colorbar_title': 'Frequency',
        'tk_net_title': 'Topics and keywords network',
        'tk_shown': 'Showing {n} topics with minimum {m} co-occurrences',
        'tk_freq_header': 'Frequency of topics and keywords',
        'tk_no_freq': 'No frequency data for topics.',
        'tk_topic_col': 'Topic/Keyword',
        'tk_freq_col': 'Frequency',
        'tk_top20': 'Top 20 most frequent topics',
        'tk_freq_dist': 'Frequency distribution',
        'tk_freq_dist_title': 'Most frequent topics and keywords',
        'tk_stats': 'Statistics',
        'tk_total': 'Total topics/keywords',
        'tk_avg_freq': 'Average frequency',
        'tk_max_freq': 'Most frequent',
        'tk_unique': 'Unique (1x)',
        'tk_conn_analysis': 'Detailed connection analysis',
        'tk_no_conn': 'No data for connection analysis.',
        'tk_topic1_col': 'Topic 1',
        'tk_topic2_col': 'Topic 2',
        'tk_cooc_col': 'Co-occurrences',
        'tk_strong_links': 'Strongest connections',
        'tk_conn_dist': 'Connection strength distribution',
        'tk_conn_dist_title': 'Distribution of co-occurrences',
        'tk_metrics': 'Network metrics',
        'tk_degree_centrality': 'Degree centrality',
        'tk_betweenness': 'Betweenness centrality',
        'tk_closeness': 'Closeness centrality',
        'tk_topic_row': 'Topic',
        'tk_top15': 'Top 15 topics by centrality',
        'tk_nodes': 'Nodes in network',
        'tk_edges': 'Edges in network',
        'tk_density': 'Density',
        'tk_avg_path': 'Average distance',
        'tk_components': 'Components',

        # ── commodity_analysis.py ─────────────────────────────────────────────────
        'ca_desc': (
            "**Analysis:** Network of commodity flows between places  \n"
            "**Nodes:** Commodities (keywords) and places  \n"
            "**Edges:** Commodity mentioned in the context of a place  \n"
            "**Goal:** Tracking trade routes and commodity exchange"
        ),
        'ca_inner_network': '🕸️ Bipartite Network',
        'ca_inner_flows': '📊 Flows',
        'ca_inner_analysis': '🔍 Analysis',
        'ca_annotation': '🟡 Commodities | 🔵 Places',
        'ca_subheader': 'Commodity Flow Analysis',
        'ca_no_data': 'Not enough data for commodity flow analysis.',
        'ca_net_header': 'Bipartite network: Commodities ↔ Places',
        'ca_no_net': 'No data to create a network.',
        'ca_settings': 'Settings',
        'ca_min_mentions': 'Minimum number of mentions:',
        'ca_show_labels': 'Show labels',
        'ca_layout_type': 'Layout type:',
        'ca_no_match': 'No connections match the criteria.',
        'ca_type_commodity': 'Commodity',
        'ca_type_place': 'Place',
        'ca_conn_label': 'Connections: {n}',
        'ca_net_title': 'Bipartite network: Commodities ↔ Places',
        'ca_flows_header': 'Commodity flow analysis',
        'ca_top_commodities': 'Top commodities by number of places',
        'ca_commodity_col': 'Commodity',
        'ca_num_places_col': 'Number of places',
        'ca_total_mentions_col': 'Total mentions',
        'ca_top_comm_title': 'Top 10 commodities by geographical spread',
        'ca_top_places': 'Top places by number of commodities',
        'ca_place_col': 'Place',
        'ca_num_commodities_col': 'Number of commodities',
        'ca_top_places_title': 'Top 10 places by commodity diversity',
        'ca_network_analysis': 'Network analysis of commodity flows',
        'ca_no_net_analysis': 'No data for network analysis.',
        'ca_node_col': 'Node',
        'ca_degree_col': 'Degree centrality',
        'ca_betweenness_col': 'Betweenness centrality',
        'ca_connections_col': 'Connections',
        'ca_top_commodities_central': 'Top commodities by centrality',
        'ca_top_places_central': 'Top places by centrality',
        'ca_net_stats': 'Network statistics',
        'ca_commodities_metric': 'Commodities',
        'ca_places_metric': 'Places',
        'ca_edges_metric': 'Connections',
        'ca_density_metric': 'Density',
        'ca_weight_dist': 'Connection strength distribution',
        'ca_weight_dist_title': 'Distribution of commodity-place mention counts',
        'ca_weight_x': 'Number of mentions',
        'ca_weight_y': 'Frequency',

        # ── temporal_analysis.py ───────────────────────────────────────────────────
        'ta_desc': (
            "**Analysis:** Evolution of communication networks over time  \n"
            "**Nodes:** Senders and addressees  \n"
            "**Edges:** Letters with timestamps  \n"
            "**Goal:** Tracking changes in communication patterns"
        ),
        'ta_inner_timeline': '📅 Timeline',
        'ta_inner_network': '🕸️ Temporal Network',
        'ta_inner_analysis': '🔍 Analysis',
        'ta_heatmap_header': 'Communication Activity Heatmap',
        'ta_month': 'Month',
        'ta_year_str': 'Year',
        'ta_color': 'Number of letters',
        'ta_subheader': 'Temporal Analysis of Communications',
        'ta_no_data': 'Not enough data with dates for temporal analysis.',
        'ta_timeline_header': 'Correspondence timeline',
        'ta_no_dates': 'No letters with valid dates.',
        'ta_settings': 'Settings',
        'ta_period': 'Period:',
        'ta_groupby': 'Group by:',
        'ta_senders': 'Senders:',
        'ta_no_period': 'No data for the selected period.',
        'ta_date_label': 'Date',
        'ta_month_label': 'Month',
        'ta_year_label': 'Year',
        'ta_letters_over_time': 'Number of letters over time (grouped by {g})',
        'ta_letters_y': 'Number of letters',
        'ta_month_x': 'Month',
        'ta_year_x': 'Year',
        'ta_color_label': 'Number of letters',
        'ta_net_header': 'Evolution of the communication network',
        'ta_no_net': 'No data for temporal network.',
        'ta_window_size': 'Time window size (days):',
        'ta_animation': 'Animation',
        'ta_layout': 'Layout algorithm:',
        'ta_select_date': 'Select date as central point:',
        'ta_no_window': 'No letters in period {s} - {e}',
        'ta_sent_label': 'Sent: {n}',
        'ta_received_label': 'Received: {n}',
        'ta_activity_label': 'Total activity: {n}',
        'ta_net_title': 'Communication network: {s} - {e} ({n} letters)',
        'ta_period_stats': 'Period statistics',
        'ta_letters_metric': 'Letters',
        'ta_participants_metric': 'Participants',
        'ta_links_metric': 'Connections',
        'ta_density_metric': 'Density',
        'ta_analysis_header': 'Temporal analysis of communications',
        'ta_no_analysis': 'No data for temporal analysis.',
        'ta_activity_header': 'Activity by participant',
        'ta_sender_y': 'Sender',
        'ta_activity_title': 'Sender activity over time',
        'ta_patterns': 'Communication patterns',
        'ta_top_links': 'Top communication connections',
        'ta_letters_dist': 'Distribution of letters over time',
        'ta_evolution_header': 'Evolution of network metrics',
        'ta_participants_trace': 'Number of participants',
        'ta_letters_trace': 'Number of letters',
        'ta_evolution_title': 'Network evolution over time',
        'ta_period_axis': 'Period',
        'ta_participants_axis': 'Number of participants',
        'ta_letters_axis': 'Number of letters',
        'ta_detail_periods': 'Detailed metrics by period',
        'ta_anim_info': 'Temporal network animation will be implemented in a future version. Please use static mode for now.',
    }
}


def get_labels(lang: str) -> dict:
    """Return the label dictionary for the given language code ('bg' or 'en')."""
    return LABELS.get(lang, LABELS['bg'])
